Feat(ruff :) Added migration from flake8 and isort to sort
osl-incubator/scicookie pull request #130
Opened 2023-06-13 21:41 UTC by ayeankit

## Pull Request description

issue solved #65 

## How to test these changes

* ```...```

## Pull Request checklists

This PR is a:
- [ ] bug-fix
- [ ] new feature
- [ ] maintenance

About this PR:
- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [ ] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:
- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more complexity.
- [ ] New and old tests passed locally.

## Additional information

## Reviewer's checklist

Copy and paste this template for your review's note:

```
## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [ ] I managed to test the new changes locally
- [ ] I confirm that the issues mentioned were fixed/resolved .
```

2023-06-13 21:52 UTC, ayeankit commented
Hey @xmnlab , I have the PR with the suggested changes.Please review the PR once again. Thank you.

2023-06-13 23:40 UTC, xmnlab commented on .pre-commit-config.yaml
> +  - repo: local
repo: local was already defined in line 7,
so you don't need to redeclare it .. neither hooks:

2023-06-13 23:42 UTC, xmnlab commented on src/scicookie/{{cookiecutter.project_slug}}/.pre-commit-config.yaml
> +      stages:
you don't need to define stages here, because it is already defined in line 6 via `default_stages`

2023-06-13 23:45 UTC, xmnlab requested changes
@ayeankit just added a few comments here
also you need to create this option in profiles/base.yaml and profiles/osl.yaml

thanks for working on that!

PS: I saw that you closed your previous PRs about ruff, any specific reason for that? because normally we just update our branch and the PR is updated automatically. also if you have any problem with rebase let me know and we can have a quick call about branch rebase.

2023-06-14 19:55 UTC, ayeankit commented
hey @xmnlab and @Saransh-cpp I have raised the PR. I don't know why it's failing the main/test. Can you please review it once again?

2023-06-14 20:45 UTC, xmnlab commented on .pre-commit-config.yaml
> +  - repo: local
Don't creat a new repo local here, instead, move ruff to the existent repo local after line 24

2023-06-14 22:12 UTC, xmnlab requested changes

2023-06-14 22:12 UTC, xmnlab commented on .pre-commit-config.yaml
> +      exclude: |
I guess you should use a different format here.
I found this: https://github.com/astral-sh/ruff/blob/main/.pre-commit-config.yaml#L53

2023-06-15 16:27 UTC, Saransh-cpp approved these changes
Nice work, thanks @ayeankit, looks good to me!

2023-06-15 16:34 UTC, ayeankit commented
@xmnlab All test cases passed, I think it's ready to merge. (it  covers #56 and #65 issues combine)

2023-06-15 17:02 UTC, xmnlab requested changes

2023-06-15 17:02 UTC, xmnlab commented on src/scicookie/{{cookiecutter.project_slug}}/.pre-commit-config.yaml
> +{%- if cookiecutter.use_ruff == 'ruff' %}
@ayeankit could you change the order of the parameters here, let's keep all options with the same structure.

And probably you can remove file.

As a follow up I will apply the same structure to the pre commit config in rhe root of the project

2023-06-15 18:18 UTC, xmnlab approved these changes
LGTM! thanks for working on that @ayeankit

2023-06-15 18:18 UTC, merged