docs(upgrade): update documentation on README.md , index.md
osl-incubator/scicookie pull request #256
Opened 2024-03-30 11:12 UTC by Satarupa22-SD

## Pull Request description

The scicookie templates aim to streamline the creation process by eliminating boilerplate structures. However, the project description was mistakenly categorized as boilerplate content. This pull request aims to rectify this misunderstanding and provide clarity regarding the project's description. 
Resolves #191

## Pull Request checklists

This PR is a:

- [x] bug-fix
- [ ] new feature
- [x] maintenance

About this PR:

- [ ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [ ] pre-commit hooks were executed locally.
- [x] this PR requires a project documentation update.

Author's checklist:

- [x] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more
      complexity.
- [ ] New and old tests passed locally.

2024-03-30 11:12 UTC, Satarupa22-SD commented
@xmnlab

2024-03-30 15:03 UTC, xmnlab commented on README.md
> +the project creation process and save considerable amount of time. Cookieninja
```suggestion
the project creation process and save considerable amount of time. SciCookie
```

2024-03-30 15:04 UTC, xmnlab commented on docs/index.md
> +the project creation process and save considerable amount of time. Cookieninja
```suggestion
the project creation process and save considerable amount of time. SciCookie
```

2024-03-30 15:04 UTC, xmnlab requested changes
thanks for working on that @Satarupa22-SD !
just added a few notes

2024-03-30 16:11 UTC, Satarupa22-SD commented
@xmnlab it's done :)

2024-03-30 17:34 UTC, xmnlab requested changes

2024-03-30 17:34 UTC, xmnlab commented on docs/index.md
> +the project creation process and save considerable amount of time. Scicookie
```suggestion
the project creation process and save considerable amount of time. SciCookie
```

2024-03-30 17:34 UTC, xmnlab commented on README.md
> +the project creation process and save considerable amount of time. Scicookie
```suggestion
the project creation process and save considerable amount of time. SciCookie
```

2024-03-30 18:47 UTC, xmnlab reviewed
@Satarupa22-SD ,
Just added a small note about the project name, it should `SciCookie`

2024-03-31 04:19 UTC, xmnlab approved these changes
LGTM! Thanks @Satarupa22-SD for working on that

2024-03-31 04:20 UTC, merged